version: "3"
services: 
  nocodb: 
    depends_on: 
      - mysql
    environment: 
      NC_DB: "mysql2://mysql:3306?u=root&p=${MYSQL_ROOT_PASSWORD}&d=root_db"
    image: "nocodb/nocodb:latest"
    ports: 
      - ${PORT}:8080
    restart: always
<% if (storage == true) { %>  
    volumes: 
      - ${DATA_PATH}:/usr/app/data
<% } _%>
  mysql: 
    environment: 
      MYSQL_DATABASE: root_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    image: "mysql:8.0.32"
    restart: always
<% if (storage == true) { %>  
    volumes: 
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
<% } _%>