version: '3.9'

services:
  flowise:
    image: flowiseai/flowise
    restart: always
    environment:
      - PORT=3000
      - PASSPHRASE=MYPASSPHRASE
      - FLOWISE_USERNAME=${FLOWISE_USERNAME}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
      - DEBUG=true
      - DATABASE_PATH=/root/.flowise
      - APIKEY_PATH=/root/.flowise
      - SECRETKEY_PATH=/root/.flowise
      - LOG_LEVEL=debug
      - LOG_PATH=/root/.flowise
    ports:
      - ${PORT}:3000
<% if (storage == true) { %>  
    volumes:
      - ${DATA_PATH}:/root/.flowise
<% } _%>
    command: /bin/sh -c "sleep 3; flowise start"