version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.4.2 # git
    container_name: pg
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
<% if (storage == true) { %>  
    volumes:
      - ${PG_DATA_PATH}:/var/lib/postgresql/data
<% } _%>
  mongo:
    image: mongo:5.0.18
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
<% if (storage == true) { %> 
    volumes:
      - ${MONGO_DATA_PATH}:/data/db
<% } _%>
  fastgpt:
    container_name: fastgpt
    image: c121914yu/fast-gpt:latest # docker hub
    ports:
      - ${PORT}:3000
    depends_on:
      - mongo
      - pg
    restart: always
    environment:
      # root 密码，用户名为: root
      - DEFAULT_ROOT_PSW=${ROOT_PASSWORD}
      # 中转地址，如果是用官方号，不需要管
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - CHAT_API_KEY=sk-xxxx
      - DB_MAX_LINK=5 # database max link
      - TOKEN_KEY=any
      - ROOT_KEY=root_key
      # mongo 配置，不需要改
      - MONGODB_URI=mongodb://username:password@mongo:27017/?authSource=admin
      - MONGODB_NAME=fastgpt
      # pg配置.
      - PG_HOST=pg
      - PG_PORT=5432
      - PG_USER=username
      - PG_PASSWORD=password
      - PG_DB_NAME=postgres