version: "3"

services:
  server:
    image: sonatype/nexus3:3.59.0
    restart: always
<% if (storage == true) { %> 
    volumes:
      - ${DATA_PATH}:/nexus-data
<% } _%>
    ports:
      - ${HTTP_PORT}:8081
