version: "3"

services:
  server:
    image: jenkins/jenkins:lts-jdk11
    restart: always
<% if (storage == true) { %> 
    volumes:
      - ${DATA_PATH}:/var/jenkins_home
<% } _%>
    ports:
      - ${HTTP_PORT}:8080
      - ${AGENT_PORT}:50000