version: '3.8'

services:
  db:
    image: mariadb:11.0
    restart: always
<% if ((storage == true) || (config == true)) { _%> 
    volumes:
<% } _%>
<% if (storage == true) { _%>  
      - ${DATA_PATH}:/var/lib/mysql
<% } _%>
<% if (config == true) { _%>   
      - ./mariadb.cnf:/etc/mysql/mariadb.cnf
<% } _%>
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - 3306:3306

<% if (admin == true) { _%>  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
<% } _%>