
version: "3.8"

services:
  dolphinscheduler-postgresql:
    image: bitnami/postgresql:15.2.0
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_DATABASE: dolphinscheduler
<% if (storage == true) { %> 
    volumes:
      - ${PG_DATA_PATH}:/bitnami/postgresql
<% } _%>
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/5432"]
      interval: 5s
      timeout: 60s
      retries: 120

  dolphinscheduler-zookeeper:
    image: bitnami/zookeeper:3.7.1
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_4LW_COMMANDS_WHITELIST: srvr,ruok,wchs,cons
<% if (storage == true) { %> 
    volumes:
      - ${ZK_DATA_PATH}:/bitnami/zookeeper
<% } _%>
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/2181"]
      interval: 5s
      timeout: 60s
      retries: 120

  dolphinscheduler-schema-initializer:
    image: apache/dolphinscheduler-tools:3.1.8
    command: [ tools/bin/upgrade-schema.sh ]
    depends_on:
      dolphinscheduler-postgresql:
        condition: service_healthy
    environment:
      TZ: "Asia/Shanghai"
      DATABASE: postgresql
      SPRING_JACKSON_TIME_ZONE: UTC
      SPRING_DATASOURCE_URL: "jdbc:postgresql://dolphinscheduler-postgresql:5432/dolphinscheduler"
      REGISTRY_ZOOKEEPER_CONNECT_STRING: dolphinscheduler-zookeeper:2181
<% if (storage == true) { %> 
    volumes:
      - ${LOG_PATH}:/opt/dolphinscheduler/logs
      - ${SHARED_PATH}:/opt/soft
      - ${RESOURCE_PATH}:/dolphinscheduler
<% } _%>

  dolphinscheduler-api:
    image: apache/dolphinscheduler-api:3.1.8
    ports:
      - "${HTTP_PORT}:12345"
      - "${GATEWAY_PORT}:25333"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:12345/dolphinscheduler/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      dolphinscheduler-zookeeper:
        condition: service_healthy
    environment:
      TZ: "Asia/Shanghai"
      DATABASE: postgresql
      SPRING_JACKSON_TIME_ZONE: UTC
      SPRING_DATASOURCE_URL: "jdbc:postgresql://dolphinscheduler-postgresql:5432/dolphinscheduler"
      REGISTRY_ZOOKEEPER_CONNECT_STRING: dolphinscheduler-zookeeper:2181
<% if (storage == true) { %> 
    volumes:
      - ${LOG_PATH}:/opt/dolphinscheduler/logs
      - ${SHARED_PATH}:/opt/soft
      - ${RESOURCE_PATH}:/dolphinscheduler
<% } _%>

  dolphinscheduler-alert:
    image: apache/dolphinscheduler-alert-server:3.1.8
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:50053/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      dolphinscheduler-zookeeper:
        condition: service_healthy
    environment:
      TZ: "Asia/Shanghai"
      DATABASE: postgresql
      SPRING_JACKSON_TIME_ZONE: UTC
      SPRING_DATASOURCE_URL: "jdbc:postgresql://dolphinscheduler-postgresql:5432/dolphinscheduler"
      REGISTRY_ZOOKEEPER_CONNECT_STRING: dolphinscheduler-zookeeper:2181
  <% if (storage == true) { %> 
    volumes:
      - ${LOG_PATH}:/opt/dolphinscheduler/logs
<% } _%>

  dolphinscheduler-master:
    image: apache/dolphinscheduler-master:3.1.8
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:5679/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      dolphinscheduler-zookeeper:
        condition: service_healthy
    environment:
      TZ: "Asia/Shanghai"
      DATABASE: postgresql
      SPRING_JACKSON_TIME_ZONE: UTC
      SPRING_DATASOURCE_URL: "jdbc:postgresql://dolphinscheduler-postgresql:5432/dolphinscheduler"
      REGISTRY_ZOOKEEPER_CONNECT_STRING: dolphinscheduler-zookeeper:2181
  <% if (storage == true) { %> 
    volumes:
      - ${LOG_PATH}:/opt/dolphinscheduler/logs
      - ${SHARED_PATH}:/opt/soft
<% } _%>

  dolphinscheduler-worker:
    image: apache/dolphinscheduler-worker:3.1.8
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:1235/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      dolphinscheduler-zookeeper:
        condition: service_healthy
    environment:
      TZ: "Asia/Shanghai"
      DATABASE: postgresql
      SPRING_JACKSON_TIME_ZONE: UTC
      SPRING_DATASOURCE_URL: "jdbc:postgresql://dolphinscheduler-postgresql:5432/dolphinscheduler"
      REGISTRY_ZOOKEEPER_CONNECT_STRING: dolphinscheduler-zookeeper:2181
  <% if (storage == true) { %> 
    volumes:
      - ${WORKER_PATH}:/tmp/dolphinscheduler
      - ${LOG_PATH}:/opt/dolphinscheduler/logs
      - ${SHARED_PATH}:/opt/soft
      - ${RESOURCE_PATH}:/dolphinscheduler
<% } _%>
