version: "3"

services:
  server:
    image: gitea/gitea:1.20.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
<% if (storage == true) { %>   
      - ${DATA_PATH}:/data
<% } _%>
      - ./timezone:/etc/timezone:ro
    ports:
      - ${HTTP_PORT}:3000
      - ${SSH_PORT}:22