version: "3"

services:
  server:
    image: gogs/gogs:latest
    restart: always
<% if (storage == true) { %>    
    volumes:
      - ${DATA_PATH}:/data
<% } _%>
    ports:
      - ${HTTP_PORT}:3000
      - ${SSH_PORT}:22