version: '3'

services:
  tooljet:
    tty: true
    stdin_open: true
    container_name: Tooljet-app
    image: tooljet/tooljet-ce:v2.13.1
    restart: always
    env_file: 
      - env
      - .env
    ports:
      - ${PORT}:80
    depends_on:
      - postgres
    environment:
      SERVE_CLIENT: "true"
      PORT: "80"
      TOOLJET_HOST: "http://localhost:${PORT}"
    command: npm run start:prod

  postgres:
    container_name: postgresql
    image: postgres:13
    restart: always
<% if (storage == true) { %> 
    volumes:
      - ${DATA_PATH}:/var/lib/postgresql/data
<% } _%>
    env_file: 
      - env
      - .env

  postgrest:
    container_name: postgrest
    image: postgrest/postgrest:v10.1.1.20221215
    restart: always
    depends_on:
      - postgres
    env_file: env
    environment:
      PGRST_SERVER_PORT: 80
