version: '3.8'

services:
  db:
    image: arangodb:3.11
<% if (storage == true) { _%>    
    volumes:
      - ${DATA_PATH}:/var/lib/arangodb3
<% } _%>
    environment:
      ARANGO_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - 8529:8529